name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        
      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test-cov
        
      - run: npm run report

      - name: Verify report existing
        run: ls coverage/lcov.info

      - name: Parallel Coveralls
        if: always()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel: true
          flag-name: run-${{ matrix.node-version }}
          

  coveralls:
    name: Coveralls Finish
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finish
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel-finished: true
